"""
Django settings for ironfort project.

Generated by 'django-admin startproject' using Django 2.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@$w)^&02&w)ro9s6^lp*j&3%c^0a7u$sqw5ozi)6^-h+omb43n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fort',
    'asset',
]

SUIT_CONFIG = {  # suit页面配置
    'ADMIN_NAME': 'Lj系统配置平台',  # 登录界面提示
    'LIST_PER_PAGE': 20,  # 表中显示行数
    'MENU': ({'label': u'用户管理', 'app': 'auth',
              'icon': 'icon-lock',  # 显示左边菜单的图标
              'models': ('auth.User', 'auth.Group')},  # 每一个字典表示左侧菜单的一栏
             {'label': u'跳板机管理', 'app': 'fort',
              'models': ('fort.Host','fort.RemoteUser','fort.RemoteUserBindHost','fort.UserProfile','fort.UserInfo','fort.Group','fort.AccessLog')},
             {'label': u'资产统计管理', 'app':  'asset',
              'models':('asset.Asset','asset.Server','asset.SecurityDevice','asset.StorageDevice','asset.NetworkDevice','asset.Software','asset.IDC','asset.Manufacturer','asset.BusinessUnit','asset.Tag','asset.CPU','asset.RAM','asset.Disk','asset.NIC','asset.EventLog')},
             ),
    # label表示name，app表示上边的install的app，models表示用了哪些models
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ironfort.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ironfort.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# import pymysql
# pymysql.install_as_MySQLdb()
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ironfort',
#         'USER': 'root',  # 用户名，可以自己创建用户
#         'PASSWORD': '!@#$QWEr1109',  # 密码
#         'HOST': '192.168.179.130',  # mysql服务所在的主机ip
#         'PORT': '3306',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
# STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(os.path.join(BASE_DIR, 'static')),
# )

STATIC_URL = '/static/'
STATIC_ROOT = 'static'
