# Generated by Django 2.0.8 on 2019-02-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('0', 'DEBUG'), ('1', 'INFO'), ('2', 'WARNING'), ('3', 'ERROR'), ('4', 'CRITICAL')], default='1', max_length=32, verbose_name='日志类型')),
                ('content', models.TextField()),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='产生日志的用户')),
            ],
            options={
                'verbose_name': '堡垒机用户行为日志',
                'verbose_name_plural': '堡垒机用户行为日志',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='主机组名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='release',
            field=models.CharField(default='CentOS', max_length=255, verbose_name='发行版本'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(max_length=128, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='fort.Group', verbose_name='所属堡垒机组'),
        ),
    ]
