# Generated by Django 2.1 on 2018-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0002_auto_20180820_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dist/img/user2-160x160.jpg', upload_to='ist/img/userhead/%Y/%m', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
